import React from 'react';
import { GiRunningNinja, GiStarShuriken, GiWhirlpoolShuriken } from 'react-icons/gi';
import { GiArcher, GiArrowWings, GiAchillesHeel } from 'react-icons/gi';
import { GiPikeman, GiPiercedBody, GiTrumpetFlag } from 'react-icons/gi';
import { GiRead, GiFireSpellCast, GiFocusedLightning } from 'react-icons/gi';


const characters = {
   Ninja: {
    name: 'Ninja',
    icon: <GiRunningNinja />,
    hp: 100,
    sp: 100,
    atk: 5,
    def: 2,
    hand1: '',
    hand2: '',
    head: '',
    chest: '',
    legs: '',
    feet: '',
    special1icon: <GiStarShuriken />,
    special1name: 'Shuriken',
    special1dmg: 20,
    special1spcost: 20,
    special1cth: 3,
    special1cc: .20,
    special2icon: <GiWhirlpoolShuriken />,
    special2name: 'Giant Shuriken',
    special2dmg: 40,
    special2spcost: 40,
    special2cth: 5,
    special2cc: .40,
    selected: 1
  },
  Archer: {
    name: 'Archer',
    icon: <GiArcher />,
    hp: 100,
    sp: 100,
    atk: 5,
    def: 2,
    hand1: '',
    hand2: '',
    head: '',
    chest: '',
    legs: '',
    feet: '',
    special1icon: <GiArrowWings />,
    special1name: 'Winged Arrow',
    special1dmg: 20,
    special1spcost: 20,
    special1cth: 3,
    special1cc: .20,
    special2icon: <GiAchillesHeel />,
    special2name: 'Achilles Heel Shot',
    special2dmg: 40,
    special2spcost: 40,
    special2cth: 5,
    special2cc: .40,
    selected: 1
  },
  Pikeman: {
    name: 'Pikeman',
    icon: <GiPikeman />,
    hp: 100,
    sp: 100,
    atk: 5,
    def: 2,
    hand1: '',
    hand2: '',
    head: '',
    chest: '',
    legs: '',
    feet: '',
    special1icon: <GiPiercedBody />,
    special1name: 'Piercing Stab',
    special1dmg: 20,
    special1spcost: 20,
    special1cth: 3,
    special1cc: .20,
    special2icon: <GiTrumpetFlag />,
    special2name: 'Pikeman Call',
    special2dmg: 40,
    special2spcost: 40,
    special2cth: 5,
    special2cc: .40,
    selected: 1
  },
  Mage: {
    name: 'Mage',
    icon: <GiRead />,
    hp: 100,
    sp: 100,
    atk: 5,
    def: 2,
    hand1: '',
    hand2: '',
    head: '',
    chest: '',
    legs: '',
    feet: '',
    special1icon: <GiFireSpellCast />,
    special1name: 'Fire Ball',
    special1dmg: 20,
    special1spcost: 20,
    special1cth: 3,
    special1cc: .20,
    special2icon: <GiFocusedLightning />,
    special2name: 'Focused Lightning',
    special2dmg: 40,
    special2spcost: 40,
    special2cth: 5,
    special2cc: .40,
    selected: 1
  }
};

export default characters;
